Update triggers
Base-de-Datos-II-CO02-Semestre-2023a/docs pull request #30
Opened 2023-05-22 03:49 UTC by arletteru

Se añadió el trigger Tipo de movimiento-movimiento

2023-05-23 01:39 UTC, hum-sc requested changes

2023-05-23 01:39 UTC, hum-sc commented on 04requerimientosSistemaERP.md
> +
Eso lo hace automaticamente postgres

2023-05-23 04:00 UTC, arletteru commented on 04requerimientosSistemaERP.md
> +
no no, el select que se le hace a la tabla padre deber ir SELECT * FROM ONLY tabla y esos son los registros que tiene si no se hace con el only salen los registros de las hijas pero como tal no se registran 'fisicamente' en la tabla padre

2023-05-25 23:25 UTC, hum-sc commented on 04requerimientosSistemaERP.md
> +
osea sí, pero no registramos fisicamente, pq al igual cuando hacemos el select de movimientos se ven todos, bueno, yo no le veo necesidad, pero si lo quieren hacer, no hay problema

2023-05-25 23:25 UTC, hum-sc approved these changes

2023-05-25 23:25 UTC, merged